<h3>Edit Category</h3>
<?php echo $this->tag->form("admin/categories/save"); ?>
<?php echo $this->tag->hiddenField(array("id")); ?>
<label for="parent_id">Parent Category</label>
<?php
echo $this->tag->select(
    array(
        "parent_id",
        $categories,
        "using" => array("id", "name"),
        "useEmpty" => true,
        'emptyText' => 'None',
        'emptyValue' => "",
        "class" => "form-control"
    )
);
?>
<label for="parent_id">Category Name</label>
<?php echo $this->tag->textField(array("name", "class" => "form-control")); ?>
<?php echo $this->tag->submitButton(array("Save", "class" => "btn btn-primary")); ?>
<?php echo $this->tag->endForm(); ?>