<table class="table table-striped">
    <thead>
        <th>Key</th>
        <th>Value</th>
        <th>Edit</th>
    </thead>
    <tbody>
    <?php foreach ($configuration as $conf): ?>
        <tr>
            <td><?php echo $conf->key; ?></td>
            <td><?php echo $conf->value; ?></td>
            <td>
                <?php echo $this->tag->linkTo('admin/configuration/edit/'. $conf->id, 'Edit') ?> |
                <?php echo $this->tag->linkTo('admin/configuration/delete/'. $conf->id, 'Delete') ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<hr>
<?php echo $this->tag->linkTo(array('admin/configuration/new/', 'New Configuration Set', 'class' => 'btn btn-primary')); ?>