<?php echo $this->tag->getDocType(); ?>
<html>
<head>
    <?php 
        echo Peregrine\Application\Helpers\MetaTag::tag(array('charset' => 'utf-8'));
        echo Peregrine\Application\Helpers\MetaTag::tag(array('http-equiv' => 'X-UA-Compatible' , 'content' => 'IE=edge"'));
        echo Peregrine\Application\Helpers\MetaTag::tag(array('viewport', 'width=device-width, initial-scale=1'));
        echo Peregrine\Application\Helpers\MetaTag::tag(array('description', 'Peregrine: Phalcon PHP based ecommerce'));
        echo Peregrine\Application\Helpers\MetaTag::tag(array('keywords', 'peregrine, phalcon, ecommerce'));
        echo $this->tag->getTitle();
        echo Phalcon\Tag::stylesheetLink("themes/default/css/bootstrap.min.css"); 
    ?>
    <!--[if lt IE 9]>
    <?php
        echo Phalcon\Tag::javascriptInclude("https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js", false);
        echo Phalcon\Tag::javascriptInclude("https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js", false);
    ?>
    <![endif]-->
    <base href="/">
</head>