<?php $this->partial("head") ?>
<body>
    <div class="container">
        <div class="row">
            <?php $this->partial("header") ?>
        </div>
        <div class="row">
            <div class="col-sm-3 sidebar">
                <div class="well">
                    <?php $this->partial("adminsidebar") ?>
                </div>
            </div>
            <div class="col-sm-9 main">
                <div class="row">
                    <?php echo $this->flash->output(); ?>
                    <?php echo $this->getContent(); ?>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <?php $this->partial("footer") ?>    
        </div>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="/themes/default/js/bootstrap.min.js"></script>
</body>
</html>