<?php $this->partial("head") ?>
<body>
    <div class="container">
        <div class="row">
            <?php $this->partial("admin/header") ?>
        </div>
        <div class="row">
            <div class="col-sm-3 sidebar">
                <div class="well">
                    <?php $this->partial("admin/sidebar") ?>
                </div>
            </div>
            <div class="col-sm-9 main">
                <div class="row">
                    <?php echo $this->flash->output(); ?>
                    <?php echo $this->getContent(); ?>
                </div>
            </div>
        </div>
    </div>
    <?php echo Phalcon\Tag::javascriptInclude("https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js", false); ?>
    <?php echo Phalcon\Tag::javascriptInclude("themes/default/js/bootstrap.min.js"); ?>
</body>
</html>