<?php echo $this->tag->getDocType(); ?>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php echo $this->tag->getTitle(); ?>
    <link href="/themes/default/css/bootstrap.min.css" rel="stylesheet">
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <base href="/"/>
</head>
<body>
    <div class="container">
        <div class="row">
            <?php $this->partial("header") ?>
        </div>
        <div class="row">
            <div class="col-sm-3 sidebar">
                <div class="well">
                    <?php $this->partial("adminsidebar") ?>
                </div>
            </div>
            <div class="col-sm-9 main">
                <div class="row">
                    <?php echo $this->flash->output(); ?>
                    <?php echo $this->getContent(); ?>
                </div>
                <div class="row">
                    <?php $this->partial("footer") ?>
                </div>
            </div>
        </div>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="/themes/default/js/bootstrap.min.js"></script>
</body>
</html>