<div class="panel panel-primary">
    <div class="panel-heading">Search</div>
    <div class="panel-body">
        <?php echo $this->tag->form("store/products/search"); ?>
        <?php echo $this->tag->textField(array("query", "class" => "form-control")); ?>
        <?php echo $this->tag->submitButton(array("Search", "class" => "btn btn-primary")); ?>
        <?php echo $this->tag->endForm(); ?>
    </div>
</div>
<div class="panel panel-primary">
    <div class="panel-heading">Categories</div>
    <div class="panel-body">
        <?php echo Peregrine\Application\Helpers\CategoryMenu::tag(); ?>
    </div>
</div>