<table class="table table-striped">
    <thead>
        <th>Id</th>
        <th>Name</th>
        <th>Edit</th>
    </thead>
    <tbody>
    <?php foreach ($products as $product): ?>
        <tr>
            <td><?php echo $product->id; ?></td>
            <td><?php echo $product->name; ?></td>
            <td>
                <?php echo $this->tag->linkTo('admin/products/edit/'. $product->id, 'Edit') ?> |
                <?php echo $this->tag->linkTo('admin/products/delete/'. $product->id, 'Delete') ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<?php echo $this->tag->linkTo(array('admin/products/new/', 'New Product', 'class' => 'btn btn-primary')); ?>