<div class="col-sm-12 products">
    <?php
    $rowcounter = 0;
    foreach ($page->items as $k => $product):
        if (!$rowcounter): ?>
            <div class="row">
        <?php
        endif;
        $rowcounter = $rowcounter + 1;
        ?>
        <div class="col-md-4 product img-thumbnail">
            <?php echo $this->partial("main/product", array('product' => $product)); ?>
        </div>
        <?php
        if ($rowcounter == 3 || $k == $page->total_items - 1):
            $rowcounter = 0;
            ?>
            </div>
        <?php
        endif;
    endforeach;
    echo $this->partial("paginator", array('controller' => '/store/products'));
    ?>
</div>