<div class="product">
	<div class="image">
	</div>
	<div class="details">
		<h4 class="title"><?php echo $product->name; ?></h4>
		<div class="description"><?php echo $product->description; ?></div>
		<div class="price">$<?php echo $product->price; ?></div>
	</div>
	<div class="images">
        <?php
        foreach($images as $k => $v) {
            echo $this->tag->image(array($v, "class" => "img-thumbnail", "width" => 250));
        }
        ?>
	</div>
</div>